### Add a parsed log entry from log line
POST http://localhost:8082/produce
Content-Type: text/plain

"Hello active MQ."

### C
POST http://localhost:8082/produce
Content-Type: text/plain

<NewTradeOrder><fromFintechCompany>1</fromFintechCompany><toFintechCompany>2</toFintechCompany><fromSalesman>1</fromSalesman><amount>1234.50</amount><type>SUB</type></NewTradeOrder>



### B
POST http://localhost:8082/produce?queue=trade-order-queue
Content-Type: text/plain

<NewTradeOrder><fromFintechCompany>1</fromFintechCompany><toFintechCompany>2</toFintechCompany><fromSalesman>1</fromSalesman><amount>1234.50</amount><type>SUB</type></NewTradeOrder>


### D
POST http://localhost:8082/produce?queue=trade-order-queue
Content-Type: text/plain

<NewTradeOrder><fromFintechCompany>2</fromFintechCompany><toFintechCompany>1</toFintechCompany><fromSalesman>1</fromSalesman><amount>12342.52</amount><type>SUB</type></NewTradeOrder>



###
"<NewTradeOrder><fromFintechCompany>1</fromFintechCompany><toFintechCompany>2</toFintechCompany><fromSalesman>1</fromSalesman><amount>1234.50</amount><type>SUB</type></NewTradeOrder>"
"
<NewTradeOrder>
    <fromFintechCompanyId>1</fromFintechCompanyId>
    <toFintechCompanyId>2</toFintechCompanyId>
    <fromSalesman>1</fromSalesman>
    <amount>1234.50</amount>
    <type>SUB</type>
</NewTradeOrder>
"
