package com.asot.springbootdemo.state.machine.enums;

public enum States {
    INITIAL,
    SERVICE_A_EXECUTING,
    SERVICE_A_OK,
    SERVICE_A_WARN,
    SERVICE_A_ERROR,
    SERVICE_A_FINISHED,
    SERVICE_A_WAITING_FOR_RETRY,
    SERVICE_A_PERMANENT_FAILURE,

    SERVICE_B_EXECUTING,
    SERVICE_B_OK,
    SERVICE_B_WARN,
    SERVICE_B_ERROR,
    SERVICE_B_FINISHED,
    SERVICE_B_WAITING_FOR_RETRY,
    SERVICE_B_PERMANENT_FAILURE,

    SERVICE_C_EXECUTING,
    SERVICE_C_OK,
    SERVICE_C_WARN,
    SERVICE_C_ERROR,
    SERVICE_C_FINISHED,
    SERVICE_C_WAITING_FOR_RETRY,
    SERVICE_C_PERMANENT_FAILURE,

    PERMANENT_FAILURE,
    FINISHED
}
